### ISSUE TITLE
add a missing migration

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-categories#10]
running ``python manage.py makemigrations aldryn_categories`` creates a new migration, so there seems to be changes not addressed in the current migrations. I suspect it's actually changes in the latest django-parler base-class that causes this.

This can cause problems when creating migrations for other apps that have relations to aldryn-categories, since Django 1.7 will sneakily create the missing migration for aldryn-categories, even if it is installed somewhere in site-packages.

**Comment by mkoistinen** [comment]
Closed by #12
