### ISSUE TITLE
Substitute django's own slugify with Unicode friendly slugify

### ISSUE THREAD

**Issue by georgema1982** [aldryn/aldryn-categories#11]
Please consider using either python-slugify (https://github.com/un33k/python-slugify) or awesome-slugify (https://github.com/dimka665/awesome-slugify) instead of django's own slugify function which is not unicode friendly. Alternatively, leave a place to configure what slugify function to use.

**Comment by mkoistinen** [comment]
This looks really nice! https://github.com/un33k/python-slugify. We have some changes coming in a post 1.0 release that will affect slugification, so, we'll probably do this then.

**Comment by georgema1982** [comment]
I guess this ticket can be closed as I notice the latest release is using python-slugfiy
