### ISSUE TITLE
Error when a category does not exist in current language

### ISSUE THREAD

**Issue by yakky** [aldryn/aldryn-categories#3]
If I try to add an instance of a model which uses ``CategoryManyToManyField`` throught the admin, and a category is not translated in the current interface language, I get the following error
https://gist.github.com/yakky/13d89d1c71938dd95d9b

**Comment by mkoistinen** [comment]
Thanks for the nice traceback. This exception is thrown when the field is asked to display something that is not a category. Can you verify precisely what it is being asked to display?

**Comment by yakky** [comment]
It's the categories field in NewsBlog (https://github.com/aldryn/aldryn-newsblog/blob/master/aldryn_newsblog/models.py#L73), nothing special.
If I create alle the languages for each category in the tree the error goes away.
Probably is caused by https://github.com/aldryn/aldryn-categories/blob/master/aldryn_categories/fields.py#L27 which does not use `obj.safe_translation_getter`

**Comment by mkoistinen** [comment]
Tests added and issue fixed.

**Comment by yakky** [comment]
Super!
